### ISSUE TITLE
Polite questions about dataset introduction

### ISSUE THREAD

**Issue by Yudezhi** [Extreme-classification/DECAF#2]
Hi:
I download the BOW and raw dataset from the link in your README file or other website ->[link](http://manikvarma.org/downloads/XC/XMLRepository.html). However I did not find the introduction file about the dataset.
For example, there are several columns in test.txt of AmazonTitles-131K, I can guess what the index mean, but I can't match it with the raw data.
I do read the original paper[McAuley et al. 2013] and some other blogs, but failed.
So, Could you please help us to explain the BOW dataset or how the raw data switch to BOW feature?

Thanks in advance!🙏

**Comment by anshumitts** [comment]
Dear @Yudezhi , thank you for showing interest in our work. You can find read me on this link.
 (please also have a look at the section titled Dataset on the XML repository ) 
https://drive.google.com/file/d/1u7YibXAC_Wz1RDehN1KjB5vu21zUnapV/view?usp=sharing

Regarding the other doubt. DECAF uses word piece tokenizer to create BoW. The entire process has been described in the paper.

Feel free to reach out we would be glad to help.

Best regards
AM

**Comment by Yudezhi** [comment]
Thanks a lot! I find it~

**Comment by Yudezhi** [comment]
Hi:
There are some data like:
label1,label2,...labelk ft1:ft1_val ft2:ft2_val ft3:ft3_val .. ftd:ftd_val
in test.txt 
1. Is this file generated by the code file 'programs/pyxclib/xclib/examples/sparse_bow_features_from_raw_data.py' ? 
Cause this file can not run correctly due to the error 'TypeError: unsupported operand type(s) for +: 'method-wrapper' and 'int'' in line 194 of text.py ,I can not to verify~
2. Could you please explain how ft1_value calculated or how the test.txt generated so that I can reimplement this function~
Thanks in advance!

**Comment by anshumitts** [comment]
Dear @Yudezhi, 
test.txt consists of two parts
label1, label2, label3 shows the relevant labels of the document while ft1:ft1_val .. shows the features. You can read the file using [pyxclib](https://github.com/kunaldahiya/pyxclib)'s read_data API. 

Regarding ft1_val these were generated using the standard WordPiece tokenizer from hugging face repo for tokenizing (Please use the vocabulary given in Xf.txt for each dataset). And Tf-IDF is a standard NLP technique and please see [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) for the documentation. 

Please note that the choice of both tokenization and Tf-IDF vectorization is user-dependent and feel free to explore other tokenizers like sentencepiece as well as feature aggregation for your task like BM25.

Best regards.
Anshul Mittal

**Comment by Yudezhi** [comment]
You mean ft1_val is the TF-IDF value?
Because the ft1_val in the test.txt is so big which did not match my experience, that's why I am here again~ hah

**Comment by anshumitts** [comment]
Can you share which dataset and value? Also, these values are not normalized.

**Comment by Yudezhi** [comment]
LF-AmazonTitles-131K/test.txt. first 2 lines as below:
134835 40000 131073
42537,43834 687:6.54914665222168 2767:10.52792358398438 5120:11.0715389251709 5260:8.709636688232422 5570:11.3969612121582 8253:9.346790313720703 11007:11.0715389251709 12502:10.03008460998535 37717:11.65932559967041



Is this because the row data are title so that TF is a little big which cause TF-IDF higher than other normal documents? But it's impossible for every ft_val bigger than 1. I am confused the relation with TF-IDF.

**Comment by Yudezhi** [comment]
BY the way, I did not find vocab file Xf.txt in row dataset. I want to generate it by myself due to some specific situation. It's similar to bert's vocab. How you generated it? Thanks~

**Comment by Yudezhi** [comment]
@anshumitts 

> BY the way, I did not find vocab file Xf.txt in row dataset. I want to generate it by myself due to some specific situation. It's similar to bert's vocab. How you generated it? Thanks~
@anshumitts

**Comment by anshumitts** [comment]
Dear @Yudezhi , I see your confusion. There are two things you are asking for.

1) **Why are TF-IDF values high?** Since this is just the title, you can assume TF=1 for almost every token in a sentence. What you are observing is the IDF value ( assumption ). For IDF computation a standard approach is
`idf=np.log2(NUM_DOCUMENTS + 1) -  np.log2(TERM_DOCUMENTS + 1) + 1` which is always greater than 1. Now, these scores are un-normalized so that users can experiment with different normalization techniques as per their needs. Once you l2 normalize these scores these values will be less than one and hopefully matches your experience. 

2) **Xf.txt file not found.** Repo contains BoW features which will have Xf.txt using which we created BoW features. Another file contains raw features which will not have Xf.txt ( for the obvious reason) and you can create new features using this file.

The complete documentation for each dataset is collectively available on the repository ([here](http://manikvarma.org/downloads/XC/XMLRepository.html)). Please check it out and let us know how we can improve things. :) 

-AM

**Comment by Yudezhi** [comment]
Thanks for your kind reply. I got a lot. 🙏
